## SWIM Configuration
[FIELDS]
project_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux'


# data folder and alternate, so local and MCO machine paths get tried
data_folder = '/media/research/IrrigationGIS/swim'
alt_data_folder = '/home/dgketchum/data/IrrigationGIS/swim'

field_index = 'FID'

# Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '1989-01-01'
end_date = '2021-12-31'

## Static file names; prepend with data_folder
input_data = 'examples/tongue/prepped_input/tongue_input_sample.json'
## Misc
elev_units = 'm'
refet_type = 'eto'

[CALIBRATION]
## PEST Calibration
calibrate_flag = 1
calibration_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue/pest/mult'
initial_values_csv = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue/params.csv'

[FORECAST]
forecast_flag = 0
forecast_parameters = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue/master/flux.5.par.csv'
