project = "3_Crane"
root = "."

[paths]
project_workspace = "{root}"
data = "{root}/data"

# SwimContainer file path
container = "{data}/{project}.swim"

landsat = "{root}/data/landsat"
landsat_tables = "{root}/data/landsat/tables"
sentinel = "{root}/data/sentinel"
sentinel_tables = "{root}/data/sentinel/tables"

met = "{root}/data/met"
gis = "{root}/data/gis"
fields_shapefile = "{root}/data/gis/flux_fields.shp"
gridmet_mapping = "{root}/data/gis/flux_fields_gfid.shp"
correction_tifs = "{root}/data/corrections"
gridmet_factors = "{root}/data/gridmet_factors.json"

properties = "{root}/data/properties"
irr = "{root}/data/properties/irr.csv"
ssurgo = "{root}/data/properties/ssurgo.csv"
lulc = "{root}/data/properties/lulc.csv"
properties_json = "{root}/data/properties/properties.json"
snodas_in = "{root}/data/snodas/extracts"
snodas_out = "{root}/data/snodas/snodas.json"

remote_sensing_tables = "{root}/data/rs_tables"
joined_timeseries = "{root}/data/plot_timeseries"
dynamics_data = "{root}/data/dynamics.json"
prepped_input = "{root}/data/prepped_input.json"

[ids]
feature_id = "FID"
gridmet_join_id = "GFID"

[misc]
irrigation_threshold = 0.3
elev_units = "m"
refet_type = "eto"
swb_mode = "cn"

[date_range]
start_date = "2003-01-01"
end_date = "2007-12-31"

[crop_coefficient]
kc_proxy = "etf"
cover_proxy = "ndvi"

[calibration]
pest_run_dir = "{project_workspace}/pestrun"
etf_target_model = "ssebop"
workers = 6
realizations = 20
calibration_dir = "{pest_run_dir}/pest/mult"
obs_folder = "{pest_run_dir}/obs"
initial_values_csv = "{pest_run_dir}/params.csv"
spinup = "{pest_run_dir}/spinup.json"
python_script = "{project_workspace}/custom_forward_run.py"

[forecast]
forecast_parameters = "{pest_run_dir}/pest/{project}.3.par.csv"
