project = "1_Boulder"
root = "."

[paths]
project_workspace = "{root}"
data = "{project_workspace}/data"

landsat = "{data}/landsat"
landsat_ee_data = "{landsat}/extracts"
landsat_tables = "{landsat}/tables"

met = "{data}/met_timeseries/gridmet"

gis = "{data}/gis"
fields_shapefile = "{gis}/mt_sid_boulder.shp"
gridmet_mapping = "{gis}/mt_sid_boulder_gfid.shp"

correction_tifs = "{data}/bias_correction_tif"
gridmet_factors = "{gis}/mt_sid_boulder_gfid.json"

properties = "{data}/properties"
irr = "{properties}/{project}_irr.csv"
ssurgo = "{properties}/{project}_ssurgo.csv"
lulc = "{properties}/{project}_landcover.csv"
properties_json = "{properties}/{project}_properties.json"

snodas_in = "{data}/snodas/extracts"
snodas_out = "{data}/snodas/snodas.json"

remote_sensing_tables = "{data}/rs_tables"
joined_timeseries = "{data}/plot_timeseries"
dynamics_data = "{data}/{project}_dynamics.json"
prepped_input = "{data}/prepped_input.json"
container = "{data}/{project}.swim"

[earth_engine]
bucket = "wudr"
drive_folder = "swim"

[ids]
feature_id = "FID_1"
gridmet_join_id = "GFID"
state_col = "STATE"

[misc]
irrigation_threshold = 0.3
elev_units = "m"
refet_type = "eto"
swb_mode = "cn"

[date_range]
start_date = "2004-01-01"
end_date = "2022-12-31"

[crop_coefficient]
kc_proxy = "etf"
cover_proxy = "ndvi"

[calibration]
etf_target_model = "ssebop"

[forecast]
